// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycarczenxnllveqwadue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljYXJjemVueG5sbHZlcXdhZHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTA0NzEsImV4cCI6MjA3MDU2NjQ3MX0.ftYbAnVsAituUv397ugTsf-RR4dFBpbfQsK6MytFUIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});