// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vspqxghwqdtakyeeiehu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzcHF4Z2h3cWR0YWt5ZWVpZWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODkxNzMsImV4cCI6MjA3MDU2NTE3M30.cy3Xf6cwLqcJ-dV-TjNsVrEQ-K9StQSuIzaPhMaogY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});